### ISSUE TITLE
Thumbnail images don't seem to be constrained

### ISSUE THREAD

**Issue by ahankinson** [DDMAL/misirlou#74] opened 2016-06-17 03:55 UTC
To Reproduce: 
Go to dev.musiclibs.net
Search 'flowers'

The thumbnail image for the first result seems to take up the whole page!

**Comment by musicus** [comment] 2016-06-17 04:36
(zucchini - hahaha)

**Comment by agpar** [comment] 2016-06-17 12:41
This can be fixed by just mandating that all search result thumbnails be 150x100. Would there be any downside to hard coding that [here?](https://github.com/DDMAL/musiclibs/blob/master/misirlou/frontend/js/components/search/result-item/thumbnail.js#L30) (Asking the frontend guys)

**Comment by agpar** [comment] 2016-06-17 12:42
(the problem is that sometimes a library provides a url for a thumbnail, other times a IIIF image service. We scale properly for IIIF, but not for raw images)

**Comment by ahankinson** [comment] 2016-06-17 12:43
Ah, thanks for that clarification. Yeah, I suppose we need to constrain it on the image tag then.

**Comment by agpar** [comment] 2016-06-17 13:02
We could _always_ ignore a thumbnail if it's a string, and instead grab some image from the middle of the manifest.

**Closed as completed** 2016-06-17 14:55 UTC
Labels: Type: Bug, Status: Waiting to be addressed, Component: Front end, Priority: High
